# before of running the bot you should create a file named `config.yaml`
# the file should be the same of this one, but replacing sample variables with true data


# the token of the bot you get from t.me/botfather (type: str)
bot_token: "token"
